version: '3'

services:
  db_postgres:
    image: postgres:15
    restart: on-failure
    volumes:
      - ./pg_db:/var/lib/postgresql@15/data/
    env_file:
      - backend/src/secrets/.env
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db_postgres
    env_file:
      - backend/src/.env
    ports:
      - "5555:5555"
  
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
      - db_postgres
    container_name: frontend-container

  nginx:
      build: ./nginx
      ports:
        - "80:80"
      depends_on:
        - backend
        - frontend
        - pgadmin
